<?php
/**
 * Created by PhpStorm.
 * User: gaupoit
 * Date: 9/26/18
 * Time: 19:40
 */

class PDACustomCI extends Wpup_UpdateServer {
	/**
	 * Override metedata.
	 *
	 * @param array $meta Metadata.
	 * @param Wpup_Request $request Request object.
	 *
	 * @return array|void
	 */
	protected function filterMetadata( $meta, $request ) {
		$meta = parent::filterMetadata( $meta, $request ); // TODO: Change the autogenerated stub.
		$meta['download_url'] = '';

		return $meta;
	}

	/**
	 * Override action download
	 *
	 * @param Wpup_Request $request Request object.
	 */
//	protected function actionDownload( Wpup_Request $request ) {
//		$this->exitWithError( 'Downloads are disable', 403 );
//	}

	/**
	 * Override load package for
	 *
	 * @param Wpup_Request $request Request object.
	 */
	protected function loadPackageFor( $request ) {
		parent::loadPackageFor( $request );
	}

	/**
	 * Process an update API request.
	 *
	 * @param array|null $query Query parameters. Defaults to the current GET request parameters.
	 * @param array|null $headers HTTP headers. Defaults to the headers received for the current request.
	 */
	public function handleRequest($query = null, $headers = null) {
		$this->startTime = microtime(true);

		$request = $this->initRequest($query, $headers);

		$this->loadPackageFor($request);
		return $this->dispatch($request);
	}

	/**
	 * Run the requested action.
	 *
	 * @param Wpup_Request $request
	 */
	protected function dispatch($request) {
		if ( $request->action === 'get_metadata' ) {
			return $this->actionGetMetadata($request);
		} else {
			$this->exitWithError(sprintf('Invalid action "%s".', htmlentities($request->action)), 400);
		}
	}


	protected function outputAsJson($response) {
		header('Content-Type: application/json; charset=utf-8');
		if ( defined('JSON_PRETTY_PRINT') ) {
			$output = json_encode($response, JSON_PRETTY_PRINT);
		} elseif ( function_exists('wsh_pretty_json') ) {
			$output = wsh_pretty_json(json_encode($response));
		} else {
			$output = json_encode($response);
		}
		return $output;
	}

	/**
	 * @param Wpup_Request $request
	 */
	protected function actionGetMetadata(Wpup_Request $request) {
		$meta = $request->package->getMetadata();
		$meta['download_url'] = $this->generateDownloadUrl($request->package);
		$meta['banners'] = $this->getBanners($request->package);
		$meta['icons'] = $this->getIcons($request->package);

		$meta = $this->filterMetadata($meta, $request);

		//For debugging. The update checker ignores unknown fields, so this is safe.
		$meta['request_time_elapsed'] = sprintf('%.3f', microtime(true) - $this->startTime);

		return $this->outputAsJson($meta);
	}

	/**
	 * Override authorization checking
	 *
	 * @param mixed $request Request object.
	 */
	protected function checkAuthorization( $request ) {
		// Comment by: thinhnp
		// Comment date: 25/01/2019
		// Reason: Need to improve it for high priority licenses.
//		try {
//			$this->logRequest( $request );
//			$license = $request->headers->get( 'Authorization' );
//			$curl    = curl_init();
//			$data    = array(
//				'license' => $license,
//			);
//			$config  = require( __DIR__ . '/../../config/index.php' );
//			$log_dir = dirname( __FILE ) . '/logs';
//			$logger  = new Katzgrau\KLogger\Logger( $log_dir );
//			curl_setopt_array( $curl, array(
//				CURLOPT_URL            => $config['api'],
//				CURLOPT_RETURNTRANSFER => true,
//				CURLOPT_ENCODING       => '',
//				CURLOPT_MAXREDIRS      => 10,
//				CURLOPT_TIMEOUT        => 30,
//				CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
//				CURLOPT_CUSTOMREQUEST  => 'POST',
//				CURLOPT_POSTFIELDS     => json_encode( $data ),
//				CURLOPT_HTTPHEADER     => array(
//					'Cache-Control: no-cache',
//					'Content-Type: application/json',
//					'X-API-KEY: ' . $config['key'],
//				),
//			) );
//			$response = curl_exec( $curl );
//			$err      = curl_error( $curl );
//			$info     = curl_getinfo( $curl );
//			curl_close( $curl );
//			if ( $err ) {
//				exit();
//			} else {
//				$logger->debug( $response );
//				$result = json_decode( $response );
//				if ( 200 !== $info['http_code'] || false === $result->message ) {
//					$logger->error( 'Response info: ' . json_encode( $info ) );
//					exit();
//				}
//			}
//		} catch ( Exception $ex ) {
//			$logger->error( wp_json_encode( $ex->getMessage() ) );
//		}
	}

}
